(()=>{
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const arr=x=>Array.isArray(x)?x:x&&typeof x==='object'?(Object.values(x).find(Array.isArray)||[]):[];
const api=(p,m='GET',b)=>fetch('/api'+p,{method:m,headers:{'Content-Type':'application/json'},body:b?JSON.stringify(b):undefined}).then(r=>{if(!r.ok)throw new Error(r.status+' '+p);return r.json().catch(()=>null)});
const inr=n=>'₹'+(+n||0).toLocaleString('en-IN');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dt=d=>d?new Date(d).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'–';
const ico=d=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="${d}"/></svg>`;
const I={home:'M3 11l9-8 9 8v10H15v-7H9v7H3z',box:'M21 8l-9-5-9 5v8l9 5 9-5zM3 8l9 5 9-5M12 13v8',swap:'M7 4l-4 4 4 4M3 8h14M17 20l4-4-4-4M21 16H7',fac:'M2 21V9l6 4V9l6 4V5h4v16z',cart:'M3 4h2l2 12h11l2-8H6M9 20h.01M17 20h.01',clock:'M12 7v5l3 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',clip:'M9 4h6v3H9zM7 5H5v16h14V5h-2M9 12h6M9 16h6',chart:'M4 20V10M10 20V4M16 20v-8M22 20H2',trend:'M3 17l6-6 4 4 8-8M15 7h6v6',pin:'M12 21s7-6 7-12a7 7 0 0 0-14 0c0 6 7 12 7 12z',dollar:'M12 2v20M17 6H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6',gear:'M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6zM19 12h2M3 12h2M12 3v2M12 19v2'};
const NAV=[['Overview',[['dashboard','Dashboard','home']]],['Operations',[['inventory','Inventory','box'],['movement','Stock Movement','swap'],['production','Production','fac']]],['Sales',[['orders','Orders','cart'],['timeline','Order Timeline','clock']]],['Procurement',[['procurement','Procurement','clip']]],['Analytics',[['reports','Reports','chart'],['kpi','KPI Summary','trend'],['tracking','Smart Tracking','pin'],['roi','ROI Calculator','dollar']]],['',[['settings','Settings','gear']]]];
$('#nav').innerHTML=NAV.map(([h,l])=>(h?`<h6>${h}</h6>`:'')+l.map(([k,n,i])=>`<a href="#${k}" data-v="${k}">${ico(I[i])}<span>${n}</span></a>`).join('')).join('');

const D={products:[],movements:[],production:[],orders:[],reports:[]};
const EP={products:'/products',movements:'/stock-movements',production:'/production',orders:'/orders',reports:'/reports'};
const load=()=>Promise.all(Object.keys(EP).map(k=>api(EP[k]).then(r=>D[k]=arr(r)).catch(e=>{D[k]=[];console.warn(e)})));
const when=x=>x.date||x.createdAt;
const pn=m=>(m.product&&m.product.itemName)||m.itemName||(D.products.find(p=>p._id===(m.product||m.productId))||{}).itemName||'–';
const tone=t=>{t=String(t).toUpperCase();return /NOT|OUT/.test(t)?'bad':/COMPLETED|CREATED|^DISPATCHED|^IN( |$)/.test(t)?'ok':'warn'};
const bg=t=>`<span class="bg ${tone(t)}">${esc(t)}</span>`;
const stat=(l,n,pre='')=>`<div class="stat"><span class="m">${l}</span><b class="big" data-n="${n}" data-pre="${pre}">0</b></div>`;
const bars=(items,key)=>{const m={};items.forEach(i=>{const k=i[key]||'—';m[k]=(m[k]||0)+1});const n=items.length||1;return Object.keys(m).length?Object.entries(m).map(([k,v])=>`<div class="br"><span>${esc(k)}</span><div class="pb"><i data-w="${Math.round(v/n*100)}"></i></div><b>${v}</b></div>`).join(''):'<p class="m">No data</p>'};
const hd=(t,s,btn='')=>`<div class="hd"><div><h1>${t}</h1><p class="m">${s}</p></div>${btn}</div>`;
const mvs=()=>[...D.movements].sort((a,b)=>new Date(when(b))-new Date(when(a)));
const stk=p=>{const s=+p.currentStock||0;return s<=0?'Out of Stock':s<=+(p.minimumStock??10)?'Low Stock':'In Stock'};
const cat=r=>r.category||'General';
let TL='';
const V={},H={};

V.dashboard=()=>{const P=D.products,O=D.orders;const low=P.filter(p=>stk(p)!=='In Stock');
return hd('Dashboard','Welcome back')+`<div class="grid">${stat('Total Stock',P.reduce((a,p)=>a+(+p.currentStock||0),0))}${stat('Stock Value',P.reduce((a,p)=>a+(+p.currentStock||0)*(+p.unitPrice||0),0),'₹')}${stat('Active Orders',O.filter(o=>o.goodsStatus!=='Dispatched').length)}${stat('In Production',D.production.filter(x=>x.status!=='COMPLETED').length)}${stat('Pending Procurement',O.filter(o=>o.type==='Purchase'&&o.goodsStatus!=='Dispatched').length)}${stat('Revenue',O.filter(o=>o.type==='Sales').reduce((a,o)=>a+(+o.amount||0),0),'₹')}</div>
<div class="two"><div class="card"><h2>Order Status Overview</h2>${bars(O,'goodsStatus')}</div><div class="card"><h2>Quick Actions</h2><div class="tb" style="margin-top:12px"><button class="btn" data-act="add-product">+ Product</button><button class="btn o" data-act="log-move">+ Movement</button><button class="btn o" data-act="new-order">+ Order</button><button class="btn o" data-act="new-prod">+ Production</button></div><h2 style="margin-top:14px">Low-stock Alerts</h2>${low.length?low.slice(0,5).map(p=>`<div class="br"><span style="width:auto;flex:1;color:var(--t)">${esc(p.itemName)}</span>${bg(stk(p))}<b>${p.currentStock}</b></div>`).join(''):'<p class="m">All stock levels healthy</p>'}</div></div>
<div class="card"><h2>Recent Activity</h2><div class="tw"><table><thead><tr><th>Date</th><th>Item</th><th>Via</th><th>Qty</th></tr></thead><tbody>${mvs().slice(0,6).map(m=>`<tr><td>${dt(when(m))}</td><td>${esc(pn(m))}</td><td>${esc(m.changedVia)}</td><td>${bg((+m.changeQuantity>=0?'IN ':'OUT ')+Math.abs(m.changeQuantity))}</td></tr>`).join('')||'<tr><td colspan="4" class="m">No activity</td></tr>'}</tbody></table></div></div>`};

V.inventory=()=>hd('Inventory','Stock count & valuation','<button class="btn" data-act="add-product">+ Add Product</button>')+`<div class="card"><div class="tb"><input id="q" class="in" placeholder="Search item…"><select id="cf" class="in"><option value="">All categories</option>${[...new Set(D.products.map(cat))].map(c=>`<option>${esc(c)}</option>`).join('')}</select><span class="m" id="val"></span></div><div class="tw"><table><thead><tr><th>Item</th><th>Category</th><th>Stock</th><th>Unit Price</th><th>Status</th><th></th></tr></thead><tbody id="pt"></tbody></table></div></div>`;
H.inventory=()=>{const draw=()=>{const q=$('#q').value.toLowerCase(),c=$('#cf').value,L=D.products.filter(p=>(!q||String(p.itemName).toLowerCase().includes(q))&&(!c||cat(p)===c));$('#val').textContent='Valuation: '+inr(D.products.reduce((a,p)=>a+(+p.currentStock||0)*(+p.unitPrice||0),0));$('#pt').innerHTML=L.map(p=>`<tr><td>${esc(p.itemName)}</td><td>${esc(cat(p))}</td><td>${p.currentStock}</td><td>${inr(p.unitPrice)}</td><td>${bg(stk(p))}</td><td><button class="ic" data-act="edit-product" data-id="${p._id}">Edit</button> <button class="ic d" data-act="del-product" data-id="${p._id}">Delete</button></td></tr>`).join('')||'<tr><td colspan="6" class="m">No products</td></tr>'};$('#q').oninput=draw;$('#cf').onchange=draw;draw()};

V.movement=()=>hd('Stock Movement','History of quantity changes','<button class="btn" data-act="log-move">+ Log Movement</button>')+`<div class="card"><div class="tb"><button class="chip on" data-f="">All</button><button class="chip" data-f="IN">IN</button><button class="chip" data-f="OUT">OUT</button></div><div class="tw"><table><thead><tr><th>Date</th><th>Item</th><th>Changed Via</th><th>Qty</th><th>Type</th><th>Changed By</th></tr></thead><tbody id="mt2"></tbody></table></div></div>`;
H.movement=()=>{const draw=f=>{$('#mt2').innerHTML=mvs().filter(m=>!f||(f==='IN')===(+m.changeQuantity>=0)).map(m=>`<tr><td>${dt(when(m))}</td><td>${esc(pn(m))}</td><td>${esc(m.changedVia)}</td><td>${m.changeQuantity}</td><td>${bg(+m.changeQuantity>=0?'IN':'OUT')}</td><td>${esc(m.changedBy)}</td></tr>`).join('')||'<tr><td colspan="6" class="m">No movements</td></tr>'};draw('');$$('.chip').forEach(c=>c.onclick=()=>{$$('.chip').forEach(x=>x.classList.toggle('on',x===c));draw(c.dataset.f)})};

V.production=()=>hd('Production','Status, progress & costing','<button class="btn" data-act="new-prod">+ New Production</button>')+`<div class="grid">${D.production.map(x=>{const w=Math.min(100,Math.round((+x.completedQuantity||0)/(+x.targetQuantity||1)*100));return`<div class="card"><div class="tb" style="margin:0 0 8px"><b>${esc(x.productName)}</b><span class="m">${esc(x.productionId)}</span></div>${bg(x.status)}<div class="br"><div class="pb"><i data-w="${w}"></i></div><b>${w}%</b></div><p class="m">${x.completedQuantity||0} / ${x.targetQuantity} units</p><p style="margin:6px 0 10px">Cost: <b>${inr(x.totalCost)}</b></p><button class="ic" data-act="edit-prod" data-id="${x._id}">Edit</button></div>`}).join('')||'<p class="m">No production records</p>'}</div>`;

const IS=['Invoice Pending','Invoice Created'],GS=['Not Dispatched','Partially Dispatched','Dispatched'];
const sel=(o,f,list)=>`<select class="in" style="padding:4px 8px" data-chg="${o._id}" data-f="${f}">${list.map(x=>`<option${o[f]===x?' selected':''}>${x}</option>`).join('')}</select>`;
V.orders=()=>hd('Orders','Sales & purchase orders','<button class="btn" data-act="new-order">+ New Order</button>')+`<div class="card"><div class="tw"><table><thead><tr><th>Transaction</th><th>Type</th><th>Party</th><th>Invoice</th><th>Goods</th><th>Amount</th><th>Date</th><th></th></tr></thead><tbody>${D.orders.map(o=>`<tr><td>${esc(o.transactionName)}</td><td>${bg(o.type)}</td><td>${esc(o.customer||o.supplier||'–')}</td><td>${sel(o,'invoiceStatus',IS)}</td><td>${sel(o,'goodsStatus',GS)}</td><td>${inr(o.amount)}</td><td>${dt(when(o))}</td><td><button class="ic" data-act="tl" data-id="${o._id}">Timeline</button></td></tr>`).join('')||'<tr><td colspan="8" class="m">No orders</td></tr>'}</tbody></table></div></div>`;

V.timeline=()=>hd('Order Timeline','Every activity on an order')+`<div class="card"><select id="ts" class="in"><option value="">Select an order…</option>${D.orders.map(o=>`<option value="${o._id}"${o._id===TL?' selected':''}>${esc(o.transactionName)}</option>`).join('')}</select><div id="tlb" style="margin-top:14px"></div></div>`;
H.timeline=()=>{const show=async()=>{const id=$('#ts').value,b=$('#tlb');TL=id;if(!id){b.innerHTML='<p class="m">Pick an order to view its timeline.</p>';return}b.innerHTML='<div class="sk"></div>';let ev=[];try{ev=arr(await api(`/orders/${id}/timeline`))}catch(e){console.warn(e)}
const o=D.orders.find(x=>x._id===id)||{};if(!ev.length){ev=[{label:'Order Created',date:when(o)}];if(o.invoiceStatus==='Invoice Created')ev.push({label:'Invoice Created'});if(o.goodsStatus&&o.goodsStatus!=='Not Dispatched')ev.push({label:o.goodsStatus})}
b.innerHTML=`<div class="tl">${ev.map((e,i)=>`<div style="--i:${i}"><b>${esc(e.title||e.activity||e.event||e.stage||e.label||e.status||e.description||e.action||'Update')}</b><p class="m">${dt(e.date||e.createdAt||e.timestamp)}</p></div>`).join('')}</div>`};$('#ts').onchange=show;show()};

V.procurement=()=>hd('Procurement','Documents, currency, reminders & approvals')+`<div class="grid">${[['📄','Documents'],['💵','Multi-Currency'],['🔔','Reminders'],['📋','Approval']].map(([e,t])=>`<div class="card fc" data-act="proc" data-t="${t}"><div class="e">${e}</div><h3>${t}</h3><p class="m">Click to open</p></div>`).join('')}</div><div class="card"><h2>Purchase Orders</h2><div class="tw"><table><thead><tr><th>Transaction</th><th>Supplier</th><th>Invoice</th><th>Goods</th><th>Amount</th></tr></thead><tbody>${D.orders.filter(o=>o.type==='Purchase').map(o=>`<tr><td>${esc(o.transactionName)}</td><td>${esc(o.supplier||'–')}</td><td>${bg(o.invoiceStatus)}</td><td>${bg(o.goodsStatus)}</td><td>${inr(o.amount)}</td></tr>`).join('')||'<tr><td colspan="5" class="m">No purchase orders</td></tr>'}</tbody></table></div></div>`;

V.reports=()=>{const c=['Sales','Purchase','Inventory','Production'];return hd('Reports',D.reports.length+' reports available')+`<div class="grid">${c.map(k=>`<div class="card fc" data-act="rf" data-c="${k}"><h3>${k}</h3>${stat('Reports',D.reports.filter(r=>r.category===k).length).replace('class="stat"','style="padding:0"')}</div>`).join('')}</div><div class="card"><div class="tb"><button class="chip on" data-c="">All</button>${c.map(k=>`<button class="chip" data-c="${k}">${k}</button>`).join('')}</div><div class="tw"><table><thead><tr><th>Report</th><th>Category</th><th>Description</th></tr></thead><tbody id="rt"></tbody></table></div></div>`};
H.reports=()=>{const draw=c=>{$('#rt').innerHTML=D.reports.filter(r=>!c||r.category===c).map(r=>`<tr><td>${esc(r.name||r.reportName||r.title)}</td><td>${bg(r.category)}</td><td class="m">${esc(r.description)}</td></tr>`).join('')||'<tr><td colspan="3" class="m">No reports</td></tr>'};draw('');$$('.chip').forEach(b=>b.onclick=()=>{$$('.chip').forEach(x=>x.classList.toggle('on',x===b));draw(b.dataset.c)})};

V.kpi=()=>{const rows=['Sales','Purchase'].map(t=>{const L=D.orders.filter(o=>o.type===t);return[t,L.length,L.reduce((a,o)=>a+(+o.amount||0),0)]}),tot=rows.reduce((a,r)=>a+r[2],0)||1;
return hd('KPI Summary','Live from your orders')+`<div class="grid">${stat('Total Orders',D.orders.length)}${stat('Dispatched',D.orders.filter(o=>o.goodsStatus==='Dispatched').length)}${stat('Invoiced',D.orders.filter(o=>o.invoiceStatus==='Invoice Created').length)}${stat('Products',D.products.length)}</div><div class="card"><h2>Order Summary</h2><div class="tw"><table><thead><tr><th></th><th>Orders (Count)</th><th>Orders (Value)</th><th style="width:30%">Share</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${inr(r[2])}</td><td><div class="pb"><i data-w="${Math.round(r[2]/tot*100)}"></i></div></td></tr>`).join('')}</tbody></table></div></div>`};

V.tracking=()=>{const O=D.orders,open=O.filter(o=>o.goodsStatus!=='Dispatched'),late=open.filter(o=>when(o)&&Date.now()-new Date(when(o))>7*864e5);
return hd('Smart Tracking','Live operational snapshot')+`<div class="grid">${stat('Orders In Progress',open.length)}${stat('Delayed Orders (7d+)',late.length)}${stat('Open Production',D.production.filter(x=>x.status!=='COMPLETED').length)}${stat('Open Purchases',open.filter(o=>o.type==='Purchase').length)}</div><div class="two"><div class="card"><h2>Production Status</h2>${bars(D.production,'status')}</div><div class="card"><h2>Procurement Status</h2>${bars(O.filter(o=>o.type==='Purchase'),'goodsStatus')}</div></div>`};

V.roi=()=>{const f=(id,l,v)=>`<label class="f"><span>${l}</span><input id="${id}" type="number" value="${v}"></label>`;
return hd('ROI Calculator','Estimate the value of StockFlow')+`<div class="two"><div class="card">${f('sl','Monthly stock loss / wastage (₹)',200000)}${f('mh','Monthly hours on manual tracking',80)}${f('hr','Hourly staff cost (₹)',400)}${f('pc','Monthly late-delivery penalties (₹)',50000)}${f('ic','Implementation cost (₹)',150000)}</div><div class="grid" style="align-content:start;grid-template-columns:1fr 1fr">${[['r1','Monthly Savings'],['r2','Annual Savings'],['r3','ROI (Year 1)'],['r4','Payback Period']].map(([i,l])=>`<div class="stat"><span class="m">${l}</span><b class="big" id="${i}">0</b></div>`).join('')}</div></div><p class="m">Assumes 90% less wastage, 70% less manual time and 80% fewer penalties.</p>`};
H.roi=()=>{const set=(id,n,pre,suf)=>{const e=$('#'+id);e.dataset.n=n;e.dataset.pre=pre;e.dataset.suf=suf;count(e)},c=()=>{const v=k=>+$('#'+k).value||0,m=v('sl')*.9+v('mh')*v('hr')*.7+v('pc')*.8,a=m*12,im=v('ic');set('r1',Math.round(m),'₹','');set('r2',Math.round(a),'₹','');set('r3',im?Math.round((a-im)/im*100):0,'','%');set('r4',m?Math.ceil(im/m):0,'',' mo')};$$('.f input').forEach(i=>i.oninput=c);c()};

V.settings=()=>hd('Settings','Preferences & data')+`<div class="two"><div class="card"><h2>Interface</h2><p class="m" style="margin:8px 0 12px">Collapse the sidebar to icons only.</p><button class="btn o" data-act="collapse">Toggle sidebar</button></div><div class="card"><h2>Data</h2><p class="m" style="margin:8px 0 12px">${D.products.length} products · ${D.orders.length} orders · ${D.production.length} production · ${D.movements.length} movements</p><button class="btn" data-act="refresh">Refresh from database</button></div></div>`;

// ---- forms & modal ----
const MD=$('#modal'),OPT=new Set(['supplier','customer','category']);
const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('on');setTimeout(()=>e.classList.remove('on'),2600)};
const closeM=()=>MD.classList.remove('on');
const fld=([n,l,t,o],v)=>`<label class="f"><span>${l}</span>${t==='select'?`<select name="${n}">${o.map(x=>{const[a,b]=Array.isArray(x)?x:[x,x];return`<option value="${esc(a)}"${String(v[n])===String(a)?' selected':''}>${esc(b)}</option>`}).join('')}</select>`:`<input name="${n}" type="${t}" value="${esc(v[n]??'')}"${t==='number'?' step="any"':''}${OPT.has(n)?'':' required'}>`}</label>`;
function modal(title,body,submit){$('#mt').textContent=title;$('#mbody').innerHTML=body;MD.classList.add('on');const f=$('#mbody form');if(f)f.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f));$$('input[type=number]',f).forEach(i=>d[i.name]=Number(i.value));try{await submit(d);closeM();await refresh();toast('Saved')}catch(er){toast('Failed: '+er.message)}}}
function form(title,fields,v,submit){modal(title,`<form>${fields.map(f=>fld(f,v)).join('')}<button class="btn" style="width:100%">Save</button></form>`,submit)}
const prodF=v=>form(v._id?'Edit Product':'Add Product',[['itemName','Item Name','text'],['category','Category','text'],['supplier','Supplier','text'],['currentStock','Current Stock','number'],['unitPrice','Unit Price (₹)','number'],['minimumStock','Minimum Stock','number']],{category:'General',minimumStock:10,...v},d=>v._id?api('/products/'+v._id,'PUT',d):api('/products','POST',d));
const PS=['PLANNED','PENDING','WIP','IN-TESTING','COMPLETED'];
const prF=v=>form(v._id?'Edit Production':'New Production',[['productionId','Production ID','text'],['productName','FG Name','text'],['targetQuantity','Target Qty','number'],['completedQuantity','Completed Qty','number'],['status','Status','select',PS],['totalCost','Total Cost (₹)','number']],{completedQuantity:0,totalCost:0,...v},d=>v._id?api('/production/'+v._id,'PUT',d):api('/production','POST',d));
const A={
go:t=>location.hash=t.dataset.v,
collapse:()=>{document.body.classList.toggle('collapsed');try{localStorage.sf=document.body.classList.contains('collapsed')?1:''}catch(e){}},
menu:()=>document.body.classList.toggle('open'),close:closeM,
refresh:async()=>{await refresh();toast('Data refreshed')},
'add-product':()=>prodF({}),
'edit-product':t=>prodF(D.products.find(p=>p._id===t.dataset.id)),
'del-product':async t=>{if(confirm('Delete this product?')){try{await api('/products/'+t.dataset.id,'DELETE');await refresh()}catch(e){toast('Failed: '+e.message)}}},
'log-move':()=>form('Log Stock Movement',[['product','Product','select',D.products.map(p=>[p._id,p.itemName])],['changedVia','Changed Via','select',['Process FG','Inward Document','Manual Adjustment','GRN / Quality Report','Sales Order','Purchase Order']],['changeQuantity','Change Quantity (negative to reduce)','number'],['changedBy','Changed By','text']],{},d=>api('/stock-movements','POST',{...d,productId:d.product})),
'new-prod':()=>prF({}),'edit-prod':t=>prF(D.production.find(x=>x._id===t.dataset.id)),
'new-order':()=>form('New Order',[['transactionName','Transaction Name','text'],['type','Type','select',['Sales','Purchase']],['amount','Amount (₹)','number'],['customer','Customer','text'],['supplier','Supplier','text'],['invoiceStatus','Invoice Status','select',IS],['goodsStatus','Goods Status','select',GS]],{},d=>api('/orders','POST',d)),
tl:t=>{TL=t.dataset.id;location.hash='timeline'},
proc:async t=>{modal(t.dataset.t,'<div class="sk"></div>');try{const r=await api('/procurement'),L=arr(r),skip=k=>k==='_id'||k==='__v';$('#mbody').innerHTML=L.length?`<div class="tw"><table><thead><tr>${Object.keys(L[0]).filter(k=>!skip(k)).slice(0,5).map(k=>`<th>${esc(k)}</th>`).join('')}</tr></thead><tbody>${L.map(x=>`<tr>${Object.keys(L[0]).filter(k=>!skip(k)).slice(0,5).map(k=>`<td>${esc(typeof x[k]==='object'?JSON.stringify(x[k]):x[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:Object.entries(r||{}).filter(([k])=>!skip(k)).map(([k,v])=>`<p><span class="m">${esc(k)}:</span> ${esc(typeof v==='object'?JSON.stringify(v):v)}</p>`).join('')||'<p class="m">No data</p>'}catch(e){$('#mbody').innerHTML='<p class="m">Could not load /api/procurement</p>'}},
rf:t=>{const b=$$('.chip').find(c=>c.dataset.c===t.dataset.c);b&&b.click()}
};
document.addEventListener('click',e=>{const t=e.target.closest('[data-act]');if(t&&A[t.dataset.act])A[t.dataset.act](t);if(e.target===MD)closeM()});
document.addEventListener('change',async e=>{const t=e.target.closest('[data-chg]');if(!t)return;try{await api('/orders/'+t.dataset.chg,'PUT',{[t.dataset.f]:t.value});const o=D.orders.find(x=>x._id===t.dataset.chg);if(o)o[t.dataset.f]=t.value;toast('Status updated')}catch(er){toast('Failed: '+er.message)}});
document.addEventListener('keydown',e=>e.key==='Escape'&&(closeM(),document.body.classList.remove('open')));

// ---- animation helpers & router ----
const RM=matchMedia('(prefers-reduced-motion:reduce)');
function count(e){const n=+e.dataset.n,pre=e.dataset.pre||'',suf=e.dataset.suf||'',t0=performance.now();const f=t=>{const k=RM.matches?1:Math.min(1,(t-t0)/900);e.textContent=pre+Math.round(n*(1-Math.pow(1-k,3))).toLocaleString('en-IN')+suf;k<1&&requestAnimationFrame(f)};requestAnimationFrame(f)}
function mount(r){$$('.card,.stat',r).forEach((e,i)=>e.style.setProperty('--i',i));$$('[data-n]',r).forEach(count);$$('[data-w]',r).forEach(e=>requestAnimationFrame(()=>requestAnimationFrame(()=>e.style.width=e.dataset.w+'%')))}
function render(){const k=V[location.hash.slice(1)]?location.hash.slice(1):'dashboard';$$('.nav a').forEach(a=>a.classList.toggle('on',a.dataset.v===k));const el=$('#view');el.innerHTML=`<div class="v">${V[k]()}</div>`;mount(el);H[k]&&H[k]();document.body.classList.remove('open');scrollTo({top:0,behavior:'smooth'})}
async function refresh(){await load();render()}
try{if(localStorage.sf)document.body.classList.add('collapsed')}catch(e){}
addEventListener('hashchange',render);
$('#view').innerHTML='<div class="sk"></div><div class="sk"></div><div class="sk"></div>';
load().then(render);
})();
